### ISSUE TITLE
parse_name error

### ISSUE THREAD

**Issue by n37r06u3** [duverse/django-cdnjs#2]
`<link rel="stylesheet" href="{% cdn "bootstrap/3.3.7" "bootstrap.min.css" %}">
`
get

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css.map">`

**Comment by duverse** [comment]
@n37r06u3 Will fix it. Thanks for reporting.

**Comment by duverse** [comment]
@n37r06u3 New version is not compatible with the previous one, but contains fix of this problem. Thanks again for reporting.
